name = "GeneralisedKoornwinderPolynomials"
uuid = "c9ef4512-0f81-49ca-92d2-a11d00265a16"
authors = ["Jiajie Yao <jjyao1106@gmail.com>"]
version = "0.1.0"

[deps]
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
BlockBandedMatrices = "ffab5731-97b5-5995-9138-79e8c1846df0"
ClassicalOrthogonalPolynomials = "b30e2e7b-c4ee-47da-9d5f-2c5c27239acd"
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
FastTransforms = "057dd010-8810-581a-b7be-e3fc3b93f78c"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
LazyBandedMatrices = "d7e5e226-e90b-4449-9968-0f923699bf6f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultivariateOrthogonalPolynomials = "4f6956fd-4f93-5457-9149-7bfc4b2ce06d"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
BandedMatrices = "1.9.4"
BenchmarkTools = "1.6.0"
BlockArrays = "1.7.1"
BlockBandedMatrices = "0.13.4"
ClassicalOrthogonalPolynomials = "0.15.3"
DomainSets = "0.7.16"
FastTransforms = "0.17.0"
ForwardDiff = "1.3.0"
LazyArrays = "2.6.2"
LazyBandedMatrices = "0.11.4"
LinearAlgebra = "1.11.0"
MultivariateOrthogonalPolynomials = "0.9.1"
Plots = "1.40.19"
Polynomials = "4.1.0"
QuadGK = "2.11.2"
Random = "1.11.0"
Revise = "3.12.3"
SparseArrays = "1.11.0"
SpecialFunctions = "2.5.1"
StaticArrays = "1.9.14"
Test = "1.11.0"
julia = "1.10, 1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
